version: "3.9"
services:
    server:
        build: .
        ports: 
            - "8080:8080"
        volumes:
            - .:/sites/terhelper
        environment:
            MY_ENV: "/sites/my!!!!"
    redis:
        image: "redis:6.2.5"
        ports: 
            - "6379:6379"
